version: "3.8"

services:
  db:
    image: mysql
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=36257
      - MYSQL_DATABASE=rentx
      - MYSQL_ROOT_PASSWORD=36257
    volumes:
      - mysql_data:/var/lib/mysql

volumes: 
  mysql_data:
    driver: local